;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                 Constants.inc                              ;
;                          True/False General Constants                      ;
;                                 Include File                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains True/False constants for the entire program
;
; Revision History:
; 04/27/22  Purvi Sehgal        Added constants and values 


.EQU   TRUE = 1          ;Sets TRUE equal to 1
.EQU   FALSE = 0         ;Sets FALSE equal to 0
